import 'styles/globals.css';

import { Montserrat, Poppins } from 'next/font/google';
import Script from 'next/script';

import { Footer } from 'components/organisms/footer/Footer';
import { Navigation } from 'components/organisms/navigation/Navigation';
import { NavigationProvider } from 'context/NavigationProvider';
import { cn } from 'lib/utils';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const montserrat = Montserrat({
  variable: '--font-montserrat',
  display: 'swap',
  subsets: ['latin'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '600', '700'],
  subsets: ['latin'],
});

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang="pl" className={cn(montserrat.variable, poppins.variable, 'font-sans')}>
    <Script src="/mailerLite.js" />
    <body className="flex min-h-screen w-screen flex-col">
      <NavigationProvider>
        <Navigation />
      </NavigationProvider>
      <main className="min-h-screen flex-1 pt-[200px]">{children}</main>

      <Footer />
    </body>
  </html>
);

export default RootLayout;
